# Generated by Django 2.0.4 on 2018-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
