# Generated by Django 2.0.4 on 2018-11-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_address_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.Person'),
        ),
    ]
