# Generated by Django 2.0.4 on 2018-07-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20180721_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='bld_grp',
            field=models.SmallIntegerField(choices=[(0, 'A+'), (1, 'B+'), (2, 'AB+'), (3, 'O+'), (4, 'A-'), (5, 'B-'), (6, 'AB-'), (7, 'O-')], max_length=1, verbose_name='Blood Group'),
        ),
    ]
