# Generated by Django 2.0.4 on 2018-08-23 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_auto_20180721_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease_drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='disease_sympton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Symptom')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('abbrv', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('disp', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='followup_drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='followup_sympton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Symptom')),
            ],
        ),
        migrations.RemoveField(
            model_name='disease',
            name='id',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='prescriptions',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='prescriptions',
        ),
        migrations.RemoveField(
            model_name='followup',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='patient',
            name='registered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic.Doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disease',
            name='scientific_name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.CharField(blank=True, max_length=250, verbose_name='Biography'),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.AddField(
            model_name='followup_sympton',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.FollowUp'),
        ),
        migrations.AddField(
            model_name='followup_drug',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.FollowUp'),
        ),
        migrations.AddField(
            model_name='followup_drug',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Drug'),
        ),
        migrations.AddField(
            model_name='disease_sympton',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Disease'),
        ),
        migrations.AddField(
            model_name='disease_drug',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Disease'),
        ),
        migrations.AddField(
            model_name='disease_drug',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Drug'),
        ),
    ]
