# Generated by Django 2.0.4 on 2018-08-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20180824_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='gift',
        ),
    ]
