# Generated by Django 2.0.4 on 2018-08-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_auto_20180824_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='profile',
            field=models.ImageField(blank=True, default='clinic/static/profile_pictures/generic-user.png', upload_to='clinic/static/clinic/user_profile'),
        ),
    ]
