# Generated by Django 2.0.4 on 2018-08-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_auto_20180824_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='human',
            old_name='bld_grp',
            new_name='blood_group',
        ),
        migrations.AlterField(
            model_name='human',
            name='profile',
            field=models.ImageField(default=None, upload_to='clinic/static/clinic/user_profile'),
        ),
    ]
