# Generated by Django 2.0.4 on 2018-08-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_auto_20180827_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='profile',
            field=models.ImageField(default=None, null=True, upload_to='clinic/static/clinic/user_profile'),
        ),
    ]
