# Generated by Django 2.0.4 on 2018-08-27 18:51

import clinic.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_auto_20180827_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=100, validators=[clinic.utils.validators.validate_password]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[clinic.utils.validators.validate_username_create]),
        ),
    ]
