# Generated by Django 2.0.4 on 2018-09-08 18:57

import clinic.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_auto_20180903_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='patient',
            name='er_number',
            field=models.BigIntegerField(blank=True, default=None, validators=[clinic.utils.validators.validate_number], verbose_name='Emergency Contact Number'),
            preserve_default=False,
        ),
    ]
