# Generated by Django 2.0.4 on 2018-09-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_auto_20180909_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='re_rel',
            new_name='er_rel',
        ),
    ]
