# Generated by Django 2.0.4 on 2018-09-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_auto_20180909_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='er_rel',
            field=models.CharField(choices=[('S', 'Sprouse'), ('F', 'Father'), ('M', 'Mother'), ('Si', 'Sibling'), ('G', 'Guardian'), ('O', 'Other')], max_length=2, verbose_name='Relationship with the Emergency contact'),
        ),
    ]
