# Generated by Django 2.0.3 on 2018-04-05 19:50

import clinic.utils.utilities
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_time', models.DateTimeField(default=clinic.utils.utilities.get_adv_date, verbose_name='Appointment Time')),
                ('place', models.CharField(choices=[('C', 'Clinic'), ('MH', 'My House'), ('TH', "Patient's House"), ('K', 'Custom')], default='C', max_length=1)),
                ('custom', models.CharField(blank=True, max_length=80, null=True, verbose_name='Custom Location')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date', models.DateField(verbose_name='Start Date')),
                ('e_date', models.DateField(blank=True, default=None, null=True, verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Complaint')),
                ('effect', models.CharField(max_length=40, verbose_name='Effect')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('abrv', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Abbreviation')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.IntegerField(null=True, verbose_name='Payment')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Follow-Up Taken At')),
                ('appointment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.Appointment')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, default='clinic/profile_pictures/generic_profile.png', upload_to='clinic/profile_pictures/')),
                ('full_name', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.IntegerField()),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='clinic.Human')),
                ('degree', models.CharField(blank=True, default='', max_length=80)),
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=250)),
            ],
            bases=('clinic.human',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clinic.Human')),
                ('relative', models.CharField(blank=True, max_length=80, null=True, verbose_name='Relative/Spouse')),
                ('emergency_contact', models.IntegerField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=40, null=True)),
            ],
            bases=('clinic.human',),
        ),
        migrations.AddField(
            model_name='complaint',
            name='followUp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.FollowUp'),
        ),
        migrations.AddField(
            model_name='case',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Disease'),
        ),
        migrations.AddField(
            model_name='followup',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Doctor'),
        ),
        migrations.AddField(
            model_name='case',
            name='doctors',
            field=models.ManyToManyField(to='clinic.Doctor'),
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient'),
        ),
    ]
