# Generated by Django 2.0.4 on 2018-07-19 16:09

import clinic.utils.utilities
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=clinic.utils.utilities.get_adv_date, verbose_name='Appointment Time')),
                ('loc', models.CharField(choices=[('C', 'Clinic'), ('h', 'House Vist'), ('v', 'Visting'), ('ct', 'Custom')], default='C', max_length=1, verbose_name='Location')),
                ('cus', models.CharField(blank=True, max_length=80, null=True, verbose_name='Custom Location')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_time', models.DateField(default=django.utils.timezone.now, verbose_name='Initial vist')),
                ('l_visit', models.DateField(blank=True, default=None, null=True, verbose_name='Last vist')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pat_comp', models.CharField(blank=True, max_length=100, null=True, verbose_name="Pratient's Complaint")),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('fee', models.PositiveSmallIntegerField(blank=True, default=100)),
                ('gift', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Follow-Up Time')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, default='clinic/profile_pictures/generic_profile.png', upload_to='clinic/profile_pictures/')),
                ('reg_time', models.DateTimeField(auto_now_add=True, verbose_name='Registration Time')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone_number', models.BigIntegerField()),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('email', models.CharField(blank=True, max_length=40, verbose_name='Email Address')),
                ('bld_grp', models.CharField(choices=[(0, 'A+'), (1, 'B+'), (2, 'AB+'), (3, 'O+'), (4, 'A-'), (5, 'B-'), (6, 'AB-'), (7, 'O-')], max_length=1, verbose_name='Blood Group')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=40)),
                ('state', models.CharField(choices=[('ap', 'Andhra Pradesh'), ('ar', 'Arunachal Pradesh'), ('as', 'Assam'), ('br', 'Bihar'), ('cg', 'Chhattisgarh'), ('ga', 'Goa'), ('gj', 'Gujarat'), ('hr', 'Haryana'), ('hp', 'Himachal Pradesh'), ('jk', 'Jammu and kashmir'), ('jh', 'Jharkhand'), ('ka', 'Karnataka'), ('kl', 'Kerala'), ('mp', 'Madhya Pradesh'), ('mh', 'Maharashtra'), ('mn', 'Manipur'), ('ml', 'Meghalaya'), ('mz', 'Mizoram'), ('nl', 'Nagaland'), ('or', 'Orissa'), ('pb', 'Punjab'), ('rj', 'Rajasthan'), ('sk', 'Sikkim'), ('tn', 'Tamil Nadu'), ('tr', 'Tripura'), ('uk', 'Uttarakhand'), ('up', 'Uttar Pradesh'), ('wb', 'West bengal'), ('tn', 'Tamil Nadu'), ('tr', 'Tripura'), ('an', 'Andaman and Nicobar Islands'), ('ch', 'Chandigarh'), ('dh', 'Dadra and Nagar Haveli'), ('dd', 'Daman and Diu'), ('dl', 'Delhi'), ('lp', 'Lakshadweep'), ('py', 'Pondicherry')], max_length=1)),
                ('country', models.CharField(choices=[('AF', 'Afghanistan'), ('AL', 'Albania'), ('DZ', 'Algeria'), ('AX', 'Aland Islands'), ('AS', 'American Samoa'), ('AI', 'Anguilla'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AN', 'Antilles - Netherlands'), ('AG', 'Antigua and Barbuda'), ('AQ', 'Antarctica'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AU', 'Australia'), ('AT', 'Austria'), ('AW', 'Aruba'), ('AZ', 'Azerbaijan'), ('bA ', 'osnia and Herzegovina'), ('BB', 'Barbados'), ('BD', 'Bangladesh'), ('BE', 'Belgium'), ('BF', 'Burkina Faso'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BI', 'Burundi'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BN', 'Brunei Darussalam'), ('BO', 'Bolivia'), ('BR', 'Brazil'), ('BS', 'Bahamas'), ('BT', 'Bhutan'), ('BV', 'Bouvet Island'), ('BW', 'Botswana'), ('BV', 'Belarus'), ('BZ', 'Belize'), ('KH', 'Cambodia'), ('CM', 'Cameroon'), ('CA', 'Canada'), ('CV', 'Cape Verde'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', 'Christmas Island'), ('CC', 'Cocos (Keeling) Islands'), ('CO', 'Colombia'), ('CG', 'Congo'), ('CI', "Cote D'Ivoire (Ivory Coast)"), ('CK', 'Cook Islands'), ('CR', 'Costa Rica'), ('HR', 'Croatia (Hrvatska)'), ('CU', 'Cuba'), ('CY', 'Cyprus'), ('CZ', 'Czech Republic'), ('CD', 'Democratic Republic of the Congo'), ('DJ', 'Djibouti'), ('DK', 'Denmark'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('SV', 'El Salvador'), ('TP', 'East Timor'), ('EE', 'Estonia'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('ET', 'Ethiopia'), ('FI', 'Finland'), ('FJ', 'Fiji'), ('FK', 'Falkland Islands (Malvinas)'), ('FM', 'Federated States of Micronesia'), ('FO', 'Faroe Islands'), ('FR', 'France'), ('FX', 'France, Metropolitan'), ('GF', 'French Guiana'), ('PF', 'French Polynesia'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('DE', 'Germany'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GB', 'Great Britain (UK)'), ('GD', 'Grenada'), ('GE', 'Georgia'), ('GR', 'Greece'), ('GL', 'Greenland'), ('GN', 'Guinea'), ('GP', 'Guadeloupe'), ('GS', 'S. Georgia and S. Sandwich Islands'), ('GT', 'Guatemala'), ('GU', 'Guam'), ('GW', 'Guinea-Bissau'), ('GY', 'Guyana'), ('HK', 'Hong Kong'), ('HM', 'Heard Island and McDonald Islands'), ('HN', 'Honduras'), ('HT', 'Haiti'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IE', 'Ireland'), ('IL', 'Israel'), ('IN', 'India'), ('IO', 'British Indian Ocean Territory'), ('IQ', 'Iraq'), ('IR', 'Iran'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JO', 'Jordan'), ('JP', 'Japan'), ('KE', 'Kenya'), ('KG', 'Kyrgyzstan'), ('KI', 'Kiribati'), ('KM', 'Comoros'), ('KN', 'Saint Kitts and Nevis'), ('KP', 'Korea (North)'), ('KR', 'Korea (South)'), ('KW', 'Kuwait'), ('KY', 'Cayman Islands'), ('KZ', 'Kazakhstan'), ('LA', 'Laos'), ('LB', 'Lebanon'), ('LC', 'Saint Lucia'), ('LI', 'Liechtenstein'), ('LK', 'Sri Lanka'), ('LR', 'Liberia'), ('LS', 'Lesotho'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('LV', 'Latvia'), ('LY', 'Libya'), ('MK', 'Macedonia'), ('MO', 'Macao'), ('MG', 'Madagascar'), ('MY', 'Malaysia'), ('ML', 'Mali'), ('MW', 'Malawi'), ('MR', 'Mauritania'), ('MH', 'Marshall Islands'), ('MQ', 'Martinique'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MT', 'Malta'), ('MX', 'Mexico'), ('MA', 'Morocco'), ('MC', 'Monaco'), ('MD', 'Moldova'), ('MN', 'Mongolia'), ('MM', 'Myanmar'), ('MP', 'Northern Mariana Islands'), ('MS', 'Montserrat'), ('MV', 'Maldives'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NC', 'New Caledonia'), ('NE', 'Niger'), ('NF', 'Norfolk Island'), ('NG', 'Nigeria'), ('NI', 'Nicaragua'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NP', 'Nepal'), ('NR', 'Nauru'), ('NU', 'Niue'), ('NZ', 'New Zealand (Aotearoa)'), ('OM', 'Oman'), ('PA', 'Panama'), ('PE', 'Peru'), ('PG', 'Papua New Guinea'), ('PH', 'Philippines'), ('PK', 'Pakistan'), ('PL', 'Poland'), ('PM', 'Saint Pierre and Miquelon'), ('CS', 'Serbia and Montenegro'), ('PN', 'Pitcairn'), ('PR', 'Puerto Rico'), ('PS', 'Palestinian Territory'), ('PT', 'Portugal'), ('PW', 'Palau'), ('PY', 'Paraguay'), ('QA', 'Qatar'), ('RE', 'Reunion'), ('RO', 'Romania'), ('RU', 'Russian Federation'), ('RW', 'Rwanda'), ('SA', 'Saudi Arabia'), ('WS', 'Samoa'), ('SH', 'Saint Helena'), ('VC', 'Saint Vincent and the Grenadines'), ('SM', 'San Marino'), ('ST', 'Sao Tome and Principe'), ('SN', 'Senegal'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SB', 'Solomon Islands'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('ES', 'Spain'), ('SD', 'Sudan'), ('SR', 'Suriname'), ('SJ', 'Svalbard and Jan Mayen'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('SY', 'Syria'), ('SU', 'USSR (former)'), ('SZ', 'Swaziland'), ('TW', 'Taiwan'), ('TZ', 'Tanzania'), ('TJ', 'Tajikistan'), ('TH', 'Thailand'), ('TL', 'Timor-Leste'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Turkey'), ('TM', 'Turkmenistan'), ('TC', 'Turks and Caicos Islands'), ('TV', 'Tuvalu'), ('UA', 'Ukraine'), ('UG', 'Uganda'), ('AE', 'United Arab Emirates'), ('UK', 'United Kingdom'), ('US', 'United States'), ('UM', 'United States Minor Outlying Islands'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistan'), ('VU', 'Vanuatu'), ('VA', 'Vatican City State'), ('VE', 'Venezuela'), ('VG', 'Virgin Islands (British)'), ('VI', 'Virgin Islands (U.S.)'), ('VN', 'Viet Nam'), ('WF', 'Wallis and Futuna'), ('EH', 'Western Sahara'), ('YE', 'Yemen'), ('YU', 'Yugoslavia (former)'), ('ZM', 'Zambia'), ('ZR', 'Zaire (former)'), ('ZW', 'Zimbabwe')], max_length=1)),
                ('pin_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('abbrv', models.CharField(max_length=10, unique=True)),
                ('disp', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('disp', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='clinic.Human')),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('speciality', models.CharField(choices=[('ped', 'Pediatrics'), ('cardio', 'Cardiologist'), ('gyno', 'Gynaecolgist'), ('neuro', 'Neurologist'), ('onco', 'Oncologist'), ('phy', 'Physician'), ('ns', 'Neuro Surgeon'), ('gs', 'General Surgeon'), ('gp', 'General Practitioner')], default='gp', max_length=1, verbose_name='Medical specialties')),
                ('qual', models.CharField(blank=True, default='', max_length=20, verbose_name='Qualification')),
                ('bio', models.CharField(blank=True, max_length=120, verbose_name='Biography')),
            ],
            bases=('clinic.human',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clinic.Human')),
                ('er_cont_name', models.CharField(blank=True, max_length=50, verbose_name='Emergency Contact Name')),
                ('relation', models.CharField(blank=True, max_length=10, verbose_name='Relation with the contact')),
                ('emergency_contact', models.BigIntegerField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=40, null=True)),
                ('med_info', models.CharField(blank=True, max_length=100, verbose_name='Medical Information')),
            ],
            bases=('clinic.human',),
        ),
        migrations.AddField(
            model_name='followup',
            name='prescriptions',
            field=models.ManyToManyField(to='clinic.Medicine'),
        ),
        migrations.AddField(
            model_name='followup',
            name='symptoms',
            field=models.ManyToManyField(to='clinic.Symptom'),
        ),
        migrations.AddField(
            model_name='disease',
            name='prescriptions',
            field=models.ManyToManyField(to='clinic.Medicine'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.ManyToManyField(to='clinic.Symptom'),
        ),
        migrations.AddField(
            model_name='case',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Disease'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinic.Case'),
        ),
        migrations.AddField(
            model_name='followup',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Doctor'),
        ),
        migrations.AddField(
            model_name='case',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Doctor'),
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Patient'),
        ),
    ]
