# Generated by Django 2.0.4 on 2018-11-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=models.ImageField(blank=True, default='user_profile/no-profile.png', upload_to='user_profile/'),
        ),
    ]
