# Generated by Django 2.0.4 on 2018-11-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20181105_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=models.ImageField(blank=True, default='clinic/static/user_profile/no-profile.png', upload_to='clinic/static/user_profile/'),
        ),
    ]
