# Generated by Django 2.0.3 on 2018-04-05 19:59

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20180406_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='from_system',
            field=models.ForeignKey(on_delete=models.SET(clinic.models.Disease.e), to='clinic.FromSys'),
        ),
    ]
