# Generated by Django 2.0.4 on 2018-11-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20181105_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='type',
            field=models.CharField(choices=[('fc', 'Free Clinic'), ('gc', 'General Clinic'), ('sc', 'Specialist Clinic')], max_length=2),
        ),
    ]
