# Generated by Django 2.0.4 on 2018-07-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20180721_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='bld_grp',
            field=models.SmallIntegerField(choices=[(0, 'A+'), (1, 'B+'), (2, 'AB+'), (3, 'O+'), (4, 'A-'), (5, 'B-'), (6, 'AB-'), (7, 'O-')], verbose_name='Blood Group'),
        ),
    ]
