# Generated by Django 2.0.4 on 2018-11-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_auto_20181105_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='visitdisease',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='visitdisease',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='visitstatement',
            name='visit',
        ),
        migrations.RenameField(
            model_name='case',
            old_name='recomnendation',
            new_name='refer',
        ),
        migrations.RenameField(
            model_name='visitcomplaint',
            old_name='name',
            new_name='complaint',
        ),
        migrations.RemoveField(
            model_name='visitcomplaint',
            name='serverity',
        ),
        migrations.AddField(
            model_name='visitdrug',
            name='dose',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VisitDisease',
        ),
        migrations.DeleteModel(
            name='VisitStatement',
        ),
        migrations.AddField(
            model_name='casedisease',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Case'),
        ),
        migrations.AddField(
            model_name='casedisease',
            name='disease',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic.Disease'),
        ),
    ]
