# Generated by Django 2.0.4 on 2018-11-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20181105_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseappointment',
            name='custom_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.Address'),
        ),
    ]
