# Generated by Django 2.0.4 on 2018-11-06 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_clinic_clinic_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('key_read', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='clinic/static/clinic/reports/')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Case')),
            ],
        ),
        migrations.CreateModel(
            name='VisitExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=25)),
                ('read', models.CharField(max_length=10, verbose_name='Reading')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.CaseVisit')),
            ],
        ),
        migrations.AlterField(
            model_name='visitdrug',
            name='dose',
            field=models.CharField(max_length=10),
        ),
    ]
