# Generated by Django 2.0.4 on 2018-11-06 16:27

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_auto_20181106_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='photo',
            field=models.ImageField(blank=True, upload_to=clinic.models.report_directory),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=models.ImageField(default='clinic/static/clinic/user_profile/no-profile.png', upload_to=clinic.models.user_profile_directory),
        ),
    ]
