# Generated by Django 2.0.4 on 2018-11-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_auto_20181106_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casereport',
            name='key_read',
            field=models.CharField(blank=True, max_length=50, verbose_name='Key Reading'),
        ),
    ]
