# Generated by Django 2.0.4 on 2018-11-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_patient_clinic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencycontactphone',
            old_name='phone_number',
            new_name='er_phone_number',
        ),
    ]
